name: apply_evermos
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  provider: ^6.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.1
  fluttertoast: ^8.0.9
  image_downloader: ^0.31.0
  image_downloader_web: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_native_splash: ^2.2.2
  flutter_gen: ^4.2.1
  flutter_gen_runner: ^4.2.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/env/
    - assets/env/.env.development
    - assets/env/.env.staging
    - assets/env/.env.production

flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
